version: '0.1.0'

networks:
  app-net

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    networks:
      - app-net
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - $HOME/ai-pentest/kafka:/tmp/kafka-logs
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    networks:
      - app-net
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: events
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    volumes:
      - $HOME/ai-pentest/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    restart: always

  neo4j:
    image: neo4j:5.26.6
    container_name: neo4j
    networks:
      - app-net
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      # NEO4J_AUTH: none
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: ["apoc"]
    volumes:
      - $HOME/ai-pentest/neo4j/data:/data
      - $HOME/ai-pentest/neo4j/logs:/logs
      - $HOME/ai-pentest/neo4j/plugins:/plugins
    restart: always
